### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by injrs0001** [itschasa/LuxuryNitro-Reseller#4]
C:\Users\***\OneDrive\Desktop\Token Bot>python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import utils
  File "C:\Users\***\OneDrive\Desktop\Token Bot\utils\__init__.py", line 1, in <module>
    from utils import config_loader
  File "C:\Users\***\OneDrive\Desktop\Token Bot\utils\config_loader.py", line 40, in <module>
    class config:
  File "C:\Users\***\OneDrive\Desktop\Token Bot\utils\config_loader.py", line 41, in config
    discord_admins: list[int]
TypeError: 'type' object is not subscriptable

**Comment by itschasa** [comment]
don't use the tool on onedrive
