### ISSUE TITLE
Idk about this. I did enable "Presence intent" and "server members intent"

### ISSUE THREAD

**Issue by BaconBoi1241** [itschasa/LuxuryNitro-Reseller#9]
Coded with <3 by chasa | https://github.com/itschasa/LuxuryNitro-Reseller
If you have any issues, create an issue using the link above. :D

Connecting to LuxuryNitro API...
Setting hit webhook...
Logging into Discord...
[2023-12-20 18:28:15] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\Gaming\Downloads\LuxuryNitro-Reseller-1.2.0\main.py", line 475, in <module>
    asyncio.run(startup())
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Gaming\Downloads\LuxuryNitro-Reseller-1.2.0\main.py", line 473, in startup
    await client.start(config.discord_token, reconnect=True)
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000017392A579B0>, 3284.25)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001739170C740>

**Comment by itschasa** [comment]
are all of these ticked?

![image](https://github.com/itschasa/LuxuryNitro-Reseller/assets/79016507/3ec4698f-33b7-4101-82b3-44ec3f4db421)

**Comment by BaconBoi1241** [comment]
All? Ah, I only enable the first two intents. I will enable the last one later on and see if it works

**Comment by BaconBoi1241** [comment]
It fixed thank you!
